[tool.poetry]
name = "aoc"
version = "0.1.0"
description = ""
authors = ["Purujit Bahl <purujit@secondspectrum.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
